tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-background": "#1a1c1c",
                "surface-container-lowest": "#ffffff",
                "on-primary-container": "#dbe7ff",
                "inverse-primary": "#a6c8ff",
                "on-tertiary-fixed-variant": "#763300",
                "on-secondary": "#ffffff",
                "tertiary": "#833900",
                "on-surface-variant": "#414752",
                "secondary-container": "#d8e3f5",
                "tertiary-container": "#a84c00",
                "inverse-surface": "#2f3131",
                "on-tertiary-fixed": "#331200",
                "surface-container-low": "#f3f3f3",
                "surface-bright": "#f9f9f9",
                "outline": "#717783",
                "on-tertiary": "#ffffff",
                "secondary-fixed-dim": "#bcc7d8",
                "surface-variant": "#e2e2e2",
                "primary-fixed-dim": "#a6c8ff",
                "on-error": "#ffffff",
                "surface-dim": "#dadada",
                "outline-variant": "#c1c6d4",
                "secondary": "#545f6e",
                "on-tertiary-container": "#ffe0d1",
                "tertiary-fixed": "#ffdbc9",
                "surface-tint": "#005eb1",
                "inverse-on-surface": "#f1f1f1",
                "primary-fixed": "#d5e3ff",
                "background": "#f9f9f9",
                "primary-container": "#0067c0",
                "on-primary-fixed-variant": "#004787",
                "on-secondary-fixed-variant": "#3d4855",
                "surface-container-high": "#e8e8e8",
                "secondary-fixed": "#d8e3f5",
                "on-surface": "#1a1c1c",
                "tertiary-fixed-dim": "#ffb68d",
                "surface-container": "#eeeeee",
                "on-error-container": "#93000a",
                "primary": "#004f96",
                "surface": "#f9f9f9",
                "on-primary": "#ffffff",
                "error": "#ba1a1a",
                "on-secondary-fixed": "#111c29",
                "on-secondary-container": "#5a6574",
                "error-container": "#ffdad6",
                "on-primary-fixed": "#001c3b",
                "surface-container-highest": "#e2e2e2"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "fontFamily": {
                "headline": ["Inter"],
                "display": ["Inter"],
                "body": ["Inter"],
                "label": ["Inter"]
            }
        },
    },
}